### ISSUE TITLE
Retoques finales

### ISSUE THREAD

**Issue by MauricioRobayo** [dimaju/registro-clientes#1]
Muy buen trabajo @dimaju .

Algunos retoques finales.

- [ ] Cambiar el nombre del repositorio a algo más descriptivo/llamativo.
- [ ] Agregar README.md con descripción del projecto y [vínculo al demo](https://dimaju.github.io/proyecto1/) y a la [página original](https://accounts.intuit.com/signup.html).
- [ ] Reemplazar la imagen por imágenes independientes, sin color de fondo.
- [ ] Usar un [formulario](https://developer.mozilla.org/es/docs/Learn/HTML/Forms/Your_first_HTML_form) para el formulario:
https://github.com/dimaju/proyecto1/blob/dfef0fcc2d4db07646450a7fdb96c7c92b23c540/index.html#L21-L22
- [ ] El borde de los botones puede verse mejor, no es exactamente el original.
- [ ] El `footer` del formulario no se ve como debería:
https://github.com/dimaju/proyecto1/blob/dfef0fcc2d4db07646450a7fdb96c7c92b23c540/index.html#L40-L42
- [ ] Para alinear las `labels` a la izquierda veo que está alineando todo el formulario hacia el centro. Podría no alinear todo hacia el centro y por defecto se va a alinear hacia la izquierda, y luego sólo alinear hacia el centro las secciones que van alineadas al centro. Puede probar inicialmente borrando esta línea:
https://github.com/dimaju/proyecto1/blob/dfef0fcc2d4db07646450a7fdb96c7c92b23c540/estilos.css#L90

**Comment by DiegoBelPe** [comment]
Saludo especial

Mauricio muchas gracias por sus valiosos aportes, me pondre a trabajar para
mejorar

**Comment by DiegoBelPe** [comment]
Cordial saludo

Mauricio como esta?

ya por fin pude subir los cambios a mi github para su revisión y valioso
aporte
https://dimaju.github.io/registro-clientes/

Sigo enfocado en mejorar y aprender dia a dia


Gracias totales
